namespace nocscienceat.JavaSimulatorOVH.Panels;

public partial class OvhPanelHandler
{
    /// <inheritdoc/>
    protected override void RegisterDataRefsAndCommands()
    {
        RegisterDataRefs(new (string, string)[]
        {
            ("Version", "sim/version/xplane_internal_version"),
            ("BAT1_V", "AirbusFBW/BatVolts[0]"),
            ("BAT2_V", "AirbusFBW/BatVolts[1]"),
            ("ApuStart_U", "AirbusFBW/OHPLightsATA49[3]"),
            ("ApuStart_L", "AirbusFBW/OHPLightsATA49[2]"),
            ("ApuMaster_U", "AirbusFBW/OHPLightsATA49[1]"),
            ("ApuMaster_L", "AirbusFBW/OHPLightsATA49[0]"),
            ("AntiIceWing_U", "AirbusFBW/OHPLightsATA30[1]"),
            ("AntiIceWing_L", "AirbusFBW/OHPLightsATA30[0]"),
            ("AntiIceEng1_U", "AirbusFBW/OHPLightsATA30[3]"),
            ("AntiIceEng1_L", "AirbusFBW/OHPLightsATA30[2]"),
            ("AntiIceEng2_U", "AirbusFBW/OHPLightsATA30[5]"),
            ("AntiIceEng2_L", "AirbusFBW/OHPLightsATA30[4]"),
            ("CrewOxy_S", "AirbusFBW/CrewOxySwitch"),
            ("CrewOxy_L", "AirbusFBW/OHPLightsATA35[1]"),
            ("Pack1_U", "AirbusFBW/OHPLightsATA21[7]"),
            ("Pack1_L", "AirbusFBW/OHPLightsATA21[6]"),
            ("ApuBleed_U", "AirbusFBW/OHPLightsATA21[5]"),
            ("ApuBleed_L", "AirbusFBW/OHPLightsATA21[4]"),
            ("Pack2_U", "AirbusFBW/OHPLightsATA21[9]"),
            ("Pack2_L", "AirbusFBW/OHPLightsATA21[8]"),
            ("Adirs1_U", "AirbusFBW/OHPLightsATA34[7]"),
            ("Adirs1_L", "AirbusFBW/OHPLightsATA34[6]"),
            ("Adirs3_U", "AirbusFBW/OHPLightsATA34[11]"),
            ("Adirs3_L", "AirbusFBW/OHPLightsATA34[10]"),
            ("Adirs2_U", "AirbusFBW/OHPLightsATA34[9]"),
            ("Adirs2_L", "AirbusFBW/OHPLightsATA34[8]"),
            ("Flap3_U", "AirbusFBW/OHPLightsATA34[18]"),
            ("Flap3_L", "AirbusFBW/OHPLightsATA34[17]"),
            ("Bat1_U", "AirbusFBW/OHPLightsATA24[10]"),
            ("Bat1_L", "AirbusFBW/OHPLightsATA24[9]"),
            ("Bat2_U", "AirbusFBW/OHPLightsATA24[12]"),
            ("Bat2_L", "AirbusFBW/OHPLightsATA24[11]"),
            ("ExtPwr_U", "AirbusFBW/OHPLightsATA24[7]"),
            ("ExtPwr_L", "AirbusFBW/OHPLightsATA24[6]"),
            ("FuelPumpLTk1_U", "AirbusFBW/OHPLightsATA28[1]"),
            ("FuelPumpLTk1_L", "AirbusFBW/OHPLightsATA28[0]"),
            ("FuelPumpLTk2_U", "AirbusFBW/OHPLightsATA28[3]"),
            ("FuelPumpLTk2_L", "AirbusFBW/OHPLightsATA28[2]"),
            ("FuelPumpCtrL_U", "AirbusFBW/OHPLightsATA28[5]"),
            ("FuelPumpCtrL_L", "AirbusFBW/OHPLightsATA28[4]"),
            ("XFeed_U", "AirbusFBW/OHPLightsATA28[15]"),
            ("XFeed_L", "AirbusFBW/OHPLightsATA28[14]"),
            ("FuelPumpCtrR_U", "AirbusFBW/OHPLightsATA28[7]"),
            ("FuelPumpCtrR_L", "AirbusFBW/OHPLightsATA28[6]"),
            ("FuelPumpRTk1_U", "AirbusFBW/OHPLightsATA28[9]"),
            ("FuelPumpRTk1_L", "AirbusFBW/OHPLightsATA28[8]"),
            ("FuelPumpRTk2_U", "AirbusFBW/OHPLightsATA28[11]"),
            ("FuelPumpRTk2_L", "AirbusFBW/OHPLightsATA28[10]"),
            ("onBAT", "AirbusFBW/ADIRUOnBat"),
            ("OvhdBrightness", "AirbusFBW/IntegratedLightLevelOHP_Raw"),
            ("LightStrobe", "AirbusFBW/OHPLightSwitches[7]"),
            ("LightBeacon", "AirbusFBW/OHPLightSwitches[0]"),
            ("LightWing", "AirbusFBW/OHPLightSwitches[1]"),
            ("LightNav", "AirbusFBW/OHPLightSwitches[2]"),
            ("LightNose", "AirbusFBW/OHPLightSwitches[3]"),
            ("LightLandL", "AirbusFBW/OHPLightSwitches[4]"),
            ("LightLandR", "AirbusFBW/OHPLightSwitches[5]"),
            ("LightRwy", "AirbusFBW/OHPLightSwitches[6]"),
            ("LightDome", "AirbusFBW/OHPLightSwitches[8]"),
            ("LightExit", "AirbusFBW/OHPLightSwitches[10]"),
            ("LightSeat", "AirbusFBW/OHPLightSwitches[11]"),
            ("LightNoSmoke", "AirbusFBW/OHPLightSwitches[12]"),
            ("AdirsNav1", "AirbusFBW/ADIRUSwitchArray[0]"),
            ("AdirsNav2", "AirbusFBW/ADIRUSwitchArray[1]"),
            ("AdirsNav3", "AirbusFBW/ADIRUSwitchArray[2]"),
            ("Wiper", "AirbusFBW/LeftWiperSwitch"),
            ("Flap3Mode", "AirbusFBW/GPWSSwitchArray[3]"),
            ("XFeedValve", "AirbusFBW/FuelOHPArray[7]"),
            ("OhpBrightness", "AirbusFBW/OHPBrightnessLevel"),
            ("IR1_Switch", "AirbusFBW/IRSwitchArray[0]"),
            ("IR2_Switch", "AirbusFBW/IRSwitchArray[1]"),
            ("IR3_Switch", "AirbusFBW/IRSwitchArray[2]"),

            // Position tracking
            ("Latitude", "sim/flightmodel/position/latitude"),
            ("Longitude", "sim/flightmodel/position/longitude")
        });

        RegisterCommands(new (string, string)[]
        {
            ("ApuStart", "toliss_airbus/apucommands/StarterToggle"),
            ("ApuMaster", "toliss_airbus/apucommands/MasterToggle"),
            ("ApuBleed", "toliss_airbus/apucommands/BleedToggle"),
            ("AntiIceWing", "toliss_airbus/antiicecommands/WingToggle"),
            ("AntiIceEng1", "toliss_airbus/antiicecommands/ENG1Toggle"),
            ("AntiIceEng2", "toliss_airbus/antiicecommands/ENG2Toggle"),
            ("CrewOxy", "sim/oxy/crew_valve_toggle"),
            ("Pack1", "toliss_airbus/aircondcommands/Pack1Toggle"),
            ("Pack2", "toliss_airbus/aircondcommands/Pack2Toggle"),
            ("Bat1", "toliss_airbus/eleccommands/Bat1Toggle"),
            ("Bat2", "toliss_airbus/eleccommands/Bat2Toggle"),
            ("ExtPwr", "toliss_airbus/eleccommands/ExtPowToggle"),
            ("FuelPumpLTk1", "toliss_airbus/fuelcommands/PumpLWing1Toggle"),
            ("FuelPumpLTk2", "toliss_airbus/fuelcommands/PumpLWing2Toggle"),
            ("FuelPumpCtrL", "toliss_airbus/fuelcommands/PumpLCenterToggle"),
            ("FuelPumpCtrR", "toliss_airbus/fuelcommands/PumpRCenterToggle"),
            ("FuelPumpRTk1", "toliss_airbus/fuelcommands/PumpRWing1Toggle"),
            ("FuelPumpRTk2", "toliss_airbus/fuelcommands/PumpRWing2Toggle"),
            ("TestEng1", "AirbusFBW/FireTestENG1"),
            ("TestEng1_Begin", "AirbusFBW/FireTestENG1_begin"),
            ("TestEng1_End", "AirbusFBW/FireTestENG1_end"),
            ("TestApu", "AirbusFBW/FireTestAPU"),
            ("TestApu_Begin", "AirbusFBW/FireTestAPU_begin"),
            ("TestApu_End", "AirbusFBW/FireTestAPU_end"),
            ("TestEng2", "AirbusFBW/FireTestENG2"),
            ("TestEng2_Begin", "AirbusFBW/FireTestENG2_begin"),
            ("TestEng2_End", "AirbusFBW/FireTestENG2_end"),
            ("CallAll", "AirbusFBW/purser/fwd"),
            ("BeaconOn", "toliss_airbus/lightcommands/BeaconOn"),
            ("BeaconOff", "toliss_airbus/lightcommands/BeaconOff")
        });
    }
}